custom/dumpsoftwareversions:
  - modules/nf-core/custom/dumpsoftwareversions/**

custom/sratoolsncbisettings:
  - modules/nf-core/custom/sratoolsncbisettings/**

fastqc:
  - modules/nf-core/fastqc/**

hisat2/align:
  - modules/nf-core/hisat2/align/**
  - modules/nf-core/hisat2/build/**
  - modules/nf-core/hisat2/extractsplicesites/**

hisat2/build:
  - modules/nf-core/hisat2/build/**
  - modules/nf-core/hisat2/extractsplicesites/**

hisat2/extractsplicesites:
  - modules/nf-core/hisat2/extractsplicesites/**

snakemake:
  - modules/nf-core/snakemake/**

sratools/fasterqdump:
  - modules/nf-core/sratools/fasterqdump/**

sratools/prefetch:
  - modules/nf-core/sratools/prefetch/**

fastq_download_prefetch_fasterqdump_sratools:
  - subworkflows/nf-core/fastq_download_prefetch_fasterqdump_sratools/**

nextflowpipelineutils:
  - subworkflows/nf-core/nextflowpipelineutils/**

nfvalidationpluginutils:
  - subworkflows/nf-core/nfvalidationpluginutils/**
